apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: meudeploy-2
    chaves: secretas
  name: meudeploy-2
  namespace: segredosdesucesso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meudeploy-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meudeploy-2
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
        resources: {}
        envFrom:
        - secretRef:
            name: meusegredo
status: {}
